import { MemoryNode } from './schema/memory.schema';

export const MEMORIES: MemoryNode[] = [
  // Lantern School Memories
  {
    id: 'school_primary_01',
    type: 'image',
    title: 'First Day Photo',
    content: 'The earliest photo of our friendship.',
    worldId: 'school',
    year: 2019,
    isSecret: false,
    position: [0.1, 0.2],
  },
  {
    id: 'school_secret_01',
    type: 'letter',
    title: 'Folded Classroom Note',
    content: 'Passed across the room during a boring lecture.',
    worldId: 'school',
    year: 2019,
    isSecret: true,
    position: [-0.3, 0.4],
  },
  {
    id: 'school_secret_02',
    type: 'image',
    title: 'Initials Carving',
    content: 'Carved initials on the wooden library desk.',
    worldId: 'school',
    year: 2020,
    isSecret: true,
    position: [0.5, -0.1],
  },
  {
    id: 'school_secret_03',
    type: 'audio',
    title: 'Distant Bell Echo',
    content: 'Audio recording of the old school bell ringing.',
    worldId: 'school',
    year: 2020,
    isSecret: true,
    position: [-0.2, -0.5],
  },

  // Steeping Room Memories
  {
    id: 'steeping_primary_01',
    type: 'video',
    title: 'Bottled Laughter Clip',
    content: 'Uncorked steam projection of uncontrolled laughing.',
    worldId: 'steeping',
    year: 2021,
    isSecret: false,
    position: [0.2, 0.6],
  },
  {
    id: 'steeping_secret_01',
    type: 'letter',
    title: 'Recipe Ledger Entry',
    content: 'Ledger of absurdity and comic failures.',
    worldId: 'steeping',
    year: 2021,
    isSecret: true,
    position: [-0.6, 0.1],
  },
  {
    id: 'steeping_secret_02',
    type: 'image',
    title: 'Midnight Tea Cup',
    content: 'Photo of late night tea brewing during exams.',
    worldId: 'steeping',
    year: 2022,
    isSecret: true,
    position: [0.4, -0.4],
  },
  {
    id: 'steeping_secret_03',
    type: 'audio',
    title: 'Rat Thief Soundbyte',
    content: 'Sound recording of the rat stealing ingredients.',
    worldId: 'steeping',
    year: 2022,
    isSecret: true,
    position: [-0.4, -0.3],
  },

  // Stillwater Memories
  {
    id: 'stillwater_primary_01',
    type: 'letter',
    title: 'The Stillwater Letter',
    content: 'Ink writing itself onto the calm water surface.',
    worldId: 'stillwater',
    year: 2023,
    isSecret: false,
    position: [0.0, 0.0],
  },
  {
    id: 'stillwater_secret_01',
    type: 'image',
    title: 'Falling Snowflake Mote',
    content: 'A frozen memory of winter evening walks.',
    worldId: 'stillwater',
    year: 2023,
    isSecret: true,
    position: [0.7, 0.3],
  },
  {
    id: 'stillwater_secret_02',
    type: 'audio',
    title: 'Stillness Piano Solo',
    content: 'Solo piano melody played in total silence.',
    worldId: 'stillwater',
    year: 2024,
    isSecret: true,
    position: [-0.7, -0.2],
  },
  {
    id: 'stillwater_secret_03',
    type: 'image',
    title: 'Water Reflection',
    content: 'A dual reflection on the basin surface.',
    worldId: 'stillwater',
    year: 2024,
    isSecret: true,
    position: [0.1, -0.7],
  },
];
